name: 'pulseops'

networks:
  pulseops:

volumes:
  repo:

services:
  pulseops1:
    image: ghcr.io/dockopslab/pulseops:latest
    environment:
      - GITHUB_URL=${GITHUB_URL}
      - GITHUB_BRANCH=${GITHUB_BRANCH}
      - GITHUB_PATH=${GITHUB_PATH}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - repo:/repo
      # - .repo:/repo
    networks:
      - pulseops
