name: 'pulseops-example'

networks:
  pulseops:

volumes:
  repo1:
  repo2:
  repo3:

services:
  pulseops1:
    image: ghcr.io/dockopslab/pulseops:latest
    env_file:
      - .git.env
    environment:
      - GITHUB_URL=github.com/dockopslab/pulseops.git
      - GITHUB_BRANCH=example/pulseops-target
      - GITHUB_PATH=watchtower/
      - CHECK_INTERVAL=3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - repo1:/repo
      # - .repo1:/repo
    networks:
      - pulseops
  
  pulseops2:
    image: ghcr.io/dockopslab/pulseops:latest
    env_file:
      - .git.env
    environment:
      - GITHUB_URL=github.com/dockopslab/pulseops.git
      - GITHUB_BRANCH=example/pulseops-target
      - GITHUB_PATH=sample/
      - CHECK_INTERVAL=120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - repo2:/repo
      # - .repo2:/repo
    networks:
      - pulseops

  pulseops3:
    image: ghcr.io/dockopslab/pulseops:latest
    env_file:
      - .git.env
    environment:
      - GITHUB_URL=github.com/dockopslab/pulseops.git
      - GITHUB_BRANCH=example/pulseops-target
      - GITHUB_PATH=sample1/
      - CHECK_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - repo3:/repo
      # - .repo3:/repo
    networks:
      - pulseops

  # ...
